### ISSUE TITLE
Transpose_seg (deconv) training

### ISSUE THREAD

**Issue by emepetres** [anilsathyan7/Portrait-Segmentation#16]
Hi, I'm interested in training the model `models/transpose_seg/deconv_bnoptimized_munet.h5`.

I've seen the model has a good ratio _resources consumption vs output_, but still I'd like to improve the results a little bit if possible.

However I don't see in the source code should I do it. I understand that `train.py` and `portrait_segmentation.ipynb` are for the _bilinear_ model, and `portrait_segmentation_v3.ipynb` for the _mnv3_seg_.

How could I generate/train the deconv one?

Thanks

**Comment by anilsathyan7** [comment]
If you check the **portrait_segmentation.ipynb**, there are two functions for convolutional blocks, i.e **deconv_block_rez** and **deconv_block**. You can simply replace one with another and try to train the same ...

**Comment by emepetres** [comment]
I see, thanks a lot!
