### ISSUE TITLE
Video models, two outputs?

### ISSUE THREAD

**Issue by emepetres** [anilsathyan7/Portrait-Segmentation#17]
Hi,

I cannot figure out why the video models published has two different outputs, why is that?

Thanks

**Comment by anilsathyan7** [comment]
Check the section: [Techniques For Improving Robustness, Accuracy and Speed](https://github.com/anilsathyan7/Portrait-Segmentation#techniques-for-improving-robustness-accuracy-and-speed) in readme and refer the related research paper for  more information.

**Comment by emepetres** [comment]
Ok thanks!
