### ISSUE TITLE
Regarding each model

### ISSUE THREAD

**Issue by Nerdyvedi** [anilsathyan7/Portrait-Segmentation#18]
Hi,
Thank you so much for uploading such a wonderful work.

I am getting a little confused as to which refers to which model?

I have the following questions

1. Is the model described in train.py the same as bilinear_fin_munet.h5 ? How did you get the .tflite model from this? When I export the train.py model I am getting a different architecture.

2. Which model does Model 1 , Model 2  and Model 3 refer to? Can you tell their corresponding saved models ?

Thank you

**Comment by anilsathyan7** [comment]
1. See the [portrait_segmentation notebook](https://github.com/anilsathyan7/Portrait-Segmentation/blob/master/portrait_segmentation.ipynb) for full code. There are two model variants in this case i.e **conv block with resize bilinear and conv block with transpose convolutions**.
2. See the corresponding saved models in the models folders.  You can check them by model specifications as described in the subsections.
**Model1 : transpose_seg
Model2: mnv3_seg
Model3: prisma_seg**
