### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by wushunshun** [anilsathyan7/Portrait-Segmentation#2]
Excuse me, I cannot download the dataset even if I use vpn. What should I do? Thank you.

**Comment by anilsathyan7** [comment]
There seems to be no issue with the links, i just double checked them both ...
The original dataset(onedrive) and my customized (google drive) can be downloaded with the above links...
I even tried using a incognito window and downloading them (no need of sigh-in).There was no problem in downloading the files...

What is the error you are getting ??

**Comment by wushunshun** [comment]
Every time I download for a while, it will automatically stop downloading. I guess it is fault of the network. I'll let my friend download it tonight. Thank you for your response very much. Can the model be test without training? Thank you again.




---Original---

**Comment by anilsathyan7** [comment]
Offcourse, you can run the last two scripts (see How to run section) for testing the model.The pretrained models are stored in models folder and the test folder contains some sample images.
Also you may run on  custom images as well. Just ensure you use  proper image format/size and   necessary libraries are installed

**Comment by wushunshun** [comment]
OK, let me try! Thank you very much! 
Best wishes!




------------------ 原始邮件 ------------------
发件人: "anilsathyan"<notifications@github.com>;
发送时间: 2019年9月20日(星期五) 晚上6:16
收件人: "anilsathyan7/Portrait-Segmentation"<Portrait-Segmentation@noreply.github.com>;
抄送: "1048276743"<1048276743@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [anilsathyan7/Portrait-Segmentation] Dataset (#2)




Offcourse, you can run the last two scripts (see How to run section) for testing the model.The pretrained models are stored in models folder and the test folder contains some sample images.
 Also you may run on  custom images as well. Just ensure you use  proper image format/size and   necessary libraries are installed

**Comment by wushunshun** [comment]
I am sorry to disturb you again. I want to ask you a question. My cuda version is 10.0. But there is a problem "Cuda driver version is insufficient for cuda for cuda runtime version" when I run the test.py.
Is any problem? My tensorflow-gpu version is 1.14.0.
Thank you. I am sorry to disturb you again.



---Original---

**Comment by anilsathyan7** [comment]
First ensure you have properly installed keras with tensorflow , along with cuda support (maybe test other programs first). You may also try running them on google colab, where all the necesary libraries are already installed

**Comment by wushunshun** [comment]
Thank you. I solved this problem. It is successful.



---Original---

**Comment by anilsathyan7** [comment]
I'am closing this issue now;but feel free to re-open/open any issues if needed ...
