### ISSUE TITLE
SlimNet

### ISSUE THREAD

**Issue by pantingchn** [anilsathyan7/Portrait-Segmentation#20]
Hi, i just wonder where can l get the training codes for SlimNet as j want to train the SlimNet by myself.

**Comment by anilsathyan7** [comment]
Please see the [slim512.ipynb](https://github.com/anilsathyan7/Portrait-Segmentation/blob/master/slim512.ipynb) notebook in the repo for training and conversion

**Comment by anilsathyan7** [comment]
To preprare the dataset for training refer : https://github.com/anilsathyan7/Portrait-Segmentation/issues/22#issuecomment-688316817
