### ISSUE TITLE
TFJS memory leak

### ISSUE THREAD

**Issue by kashikarparth** [anilsathyan7/Portrait-Segmentation#21]
Running inference in the browser leads to a memory leak issue, as GPU allocated memory rises continuously.

**Comment by anilsathyan7** [comment]
Can you check the latest commit... Now it reaches around 40 percent of memory and  seems to deallocate the used up memory.

**Comment by kashikarparth** [comment]
Thank you for the quick response! Its now exhibiting any memory leaks now.
