### ISSUE TITLE
prisma_segmentation dataset

### ISSUE THREAD

**Issue by DonkeySmall** [anilsathyan7/Portrait-Segmentation#25]
Hi, where can i get dataset for prisma_segmentation notebook?

**Comment by anilsathyan7** [comment]
Check out this link: https://drive.google.com/file/d/1FQHaMrsFyxUv5AtwjfPD0gtmEVFM7w3X/view?usp=sharing

**Comment by DonkeySmall** [comment]
Thanks a lot
