### ISSUE TITLE
Increase segmentation accuracy

### ISSUE THREAD

**Issue by DonkeySmall** [anilsathyan7/Portrait-Segmentation#28]
Hi, thank you very much for your previous help. How can I significantly increase segmentation accuracy of the slim512 network, speed is not important in principle, I need a very high segmentation accuracy and the ability to convert the model to TFLite.

**Comment by anilsathyan7** [comment]
There's no silver bullet; you need to experiment on various parameter settings and compare their results. Anyway, here are some suggestions:-

1. May be use better and bigger datasets/ input image size to suit your use case. 
2. Use advanced training techniques like boundary loss, temporal consistency etc.
3. Make the model deeper/ bigger by adding layers, increasing number of filters etc.

Also try out  heavier models like deeplab,  bisnet, boundary-aware network etc. if speed is not an issue...

**Comment by DonkeySmall** [comment]
Thanks, I probably won't be able to do it, I'll try to figure it out.

**Comment by DonkeySmall** [comment]
How can I for example use resnet18 or vgg16 to train the model?

**Comment by anilsathyan7** [comment]
I would suggest you to look at the working of basic encoder decoder networks and how to use popular networks like mobilenet or resnet as backbone  for segmentaion tasks.

**Comment by DonkeySmall** [comment]
Thanks, i use DeeplabV3Plus now
