### ISSUE TITLE
Training dataset for the deconv_bnoptimized_munet.h5 model?

### ISSUE THREAD

**Issue by SamSamhuns** [anilsathyan7/Portrait-Segmentation#34]
Just want to premise by saying that this is excellent work @anilsathyan7 . 

However, after reading the README, I am still a bit confused about what dataset was used for training the `deconv_bnoptimized_munet.h5` model? 

I am guessing it was the `training data-set` at <https://drive.google.com/file/d/1UBLzvcqvt_fin9Y-48I_-lWQYfYpt_6J/view?usp=sharing> that you have in the README. 

But what datasets the `img_uint8.npy` and `msk_uint8.npy` files based on, is it the augmented PFCN or AI Segment or the PASCAL VOC Person?

Thanks!

**Comment by anilsathyan7** [comment]
I think it was a custom dataset based on pfcn and supervisely.

**Comment by SamSamhuns** [comment]
Thanks for the reply, so the `deconv_bnoptimized_munet.h5` model is trained on the pfcn and supervisely dataset?

**Comment by anilsathyan7** [comment]
Yes, pfcn and selected supevisely images augmented with other backgrounds(composting)
