### ISSUE TITLE
Difference in mobilenet_v3.py

### ISSUE THREAD

**Issue by haowang1013** [anilsathyan7/Portrait-Segmentation#35]
Hi,

I noticed that you're using a custom mobilenet_v3.py rather than the default one from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/mobilenet_v3.py

I compared the 2 and the only meaningful difference is on this line: https://github.com/anilsathyan7/Portrait-Segmentation/blob/master/MobilenetV3/mobilenet_v3.py#L258

Could you explain why your version has this line commented out?

**Comment by anilsathyan7** [comment]
Refer the corresponding ipynb notebook.
