### ISSUE TITLE
SavedModel checkpoints of Slimnet

### ISSUE THREAD

**Issue by Nerdyvedi** [anilsathyan7/Portrait-Segmentation#37]
Hi, It would be great if you could share the SavedModel format checkpoints of Slimnet. 
I want to try and test the quantised model.

Thank you

**Comment by anilsathyan7** [comment]
This is the tf.keras checkpoint file(hdf5): https://github.com/anilsathyan7/Portrait-Segmentation/blob/master/models/slim_seg_512/slim-net-157-0.02.hdf5

Maybe, you can load this chekpoint and save it in tf SavedModel format ....
