### ISSUE TITLE
How are the SINet.onnx and SINet_Softmax.onnx files created? 

### ISSUE THREAD

**Issue by Ajay-Reva** [anilsathyan7/Portrait-Segmentation#39]
I am working on model conversion for different platforms using your repository. This exact [SINet.onnx](https://github.com/anilsathyan7/Portrait-Segmentation/blob/master/SINet/SINet.onnx) version works (and SINet_Softmax.onnx also works!). The [SINet_ONNX.ipynb](https://github.com/anilsathyan7/Portrait-Segmentation/blob/master/SINet/SINet_ONNX.ipynb) script exports onnx which I am not able to convert.  

How exactly did you create SINet.onnx and SINet_Softmax.onnx?

**Comment by anilsathyan7** [comment]
What is the error?
I hope you read the note section in the ipynb


> Note: The original SINet class file was modified at line 116, i.e x.size() to [int(s) for s in x.size()] . This makes the size value static and prevents error during onnx conversion. Also, some layers like ReduceMax may not be fully supported in opencv onnx runtime, so replace this operation with appropriate reshape and maxpool layers.

**Comment by Ajay-Reva** [comment]
There was a simple problem of ONNX compatibility with pytorch model.
