### ISSUE TITLE
making mask of the pictures

### ISSUE THREAD

**Issue by arunxz98** [anilsathyan7/Portrait-Segmentation#4]
Hi, @anilsathyan7 ,
i'm trying to train with 224*224 images of small dataset, can you please help me in creating masks, of the pictures that i have? i've been to the deep lab demo.ipynb in the acknowledgements that you mentioned, i'm kind of in a grey area of what mask images are needed to be taken and considered for conversion, along with the source image.

**Comment by anilsathyan7** [comment]
How many images and classes are there? If you are familiar with tools like Gimp or Photoshop you can easily use their default  plugins to create a binary mask.

Here is one such method in gimp:-
1. Use 'Intelligent Scissors' from selection tools in tools menu [ I ].
2. Select the required enclosing area (zoom & select boundary) and use 'Fill with BG Color' (white) from edit menu [ Ctrl+. ].
3. Invert the selection from selection menu [ Ctrl+I ]. 
4. Now use 'Fill with FG Color' (black),from edit menu [ Ctrl+, ]
5. Export the image as 'png'

* Initially, ensure 'anti-aliasing' is unselected in tool options.
* Finally, verify that the saved images are 'binary' (i.e 0,255). Either visualize the histogram or print pixel values using python for the same.
