### ISSUE TITLE
Slimnet pre-trained model questions

### ISSUE THREAD

**Issue by ari-ruokamo** [anilsathyan7/Portrait-Segmentation#43]
Hi! And thanks for your amazing source of DL information. I'm exploring the repository and the pre-trained 'slim_reshape.tflite' model.

In my python script I'm feeding input of 512x512x3 RGB-frame but I can't seem to get any sensible result out from the model. I'm suspecting that my input tensor data array is ill-formatted, or I'm interpreting the output tensor wrong (alpha mask?). 

Thanks for any tips!

**Comment by anilsathyan7** [comment]
The exported model had some issue, it seems. Now it has been fixed and you can try the updated versions of the model from the same folder. A slightly different version of the model(output shape) is available at: https://github.com/anilsathyan7/Portrait-Segmentation/blob/master/mediapipe_slimnet/portrait_segmentation.tflite

**Comment by ari-ruokamo** [comment]
Thanks for your response! I picked up the updated model from /models/slim_seg_512/ folder. I'm facing the same problem, how can I obtain the alpha mask from the model output? What I get is surely not correct. The output is a frame of (moving) vertical grayscale lines.

Thanks!

```

while True:
    
    # Read webcam frame 
    success, frame = cap.read()
    image = center_crop_resize(frame, side=512)
    image = np.float32(image)/255

    expimg = image[np.newaxis, :, :, :]

    # Invoke interpreter for inference
    interpreter.set_tensor(input_details[0]['index'], np.array(expimg, dtype=np.float32))
    interpreter.invoke()
    output = interpreter.get_tensor(output_details[0]['index'])

    # Reshape byte buffer & display the mask
    output = np.uint8(output*255.0)
    output = cv2.resize(output, size, 1)
    cv2.imshow('Portrait Mask', output)

```

**Comment by ari-ruokamo** [comment]
Issue author error, model works.
